- apt_key:
    id: 561F9B9CAC40B2F7
    keyserver: hkp://keyserver.ubuntu.com:80
  sudo: yes

- apt:
    name: apt-transport-https
    state: present
  sudo: yes

- apt:
    name: ca-certificates
    state: present
  sudo: yes

- lineinfile:
    create: yes
    dest: /etc/apt/sources.list.d/passenger.list
    line: deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main
    state: present
  sudo: yes

- apt:
    name: libapache2-mod-passenger
    state: present
  sudo: yes

- file:
    path: /etc/apache2/mods-enabled/passenger.conf
    src: /etc/apache2/mods-available/passenger.conf
    state: link
  sudo: yes

- file:
    path: /etc/apache2/mods-enabled/passenger.load
    src: /etc/apache2/mods-available/passenger.load
    state: link
  sudo: yes

- service:
    name: apache2
    state: restarted
  sudo: yes
