- apt:
    name: apt-transport-https
    state: present
  become: true

- apt:
    name: ca-certificates
    state: present
  become: true

- apt:
    name: curl
    state: present
  become: true

- apt:
    name: software-properties-common
    state: present
  become: true

- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  become: true

- apt:
    name: docker-ce=17.06.2~ce-0~ubuntu
    state: present
  become: true

- user:
    append: yes
    groups: docker
    name: vagrant
  become: true
