VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.define "hunnor", autostart: false do |hunnor|
		hunnor.vm.box = "box-cutter/ubuntu1604"
		hunnor.vm.hostname = "hunnor"
		hunnor.vm.autostart = false
		hunnor.vm.network "forwarded_port", guest:   80, host: 1080
		hunnor.vm.network "forwarded_port", guest: 3000, host: 3000
		hunnor.vm.network "forwarded_port", guest: 8080, host: 8080
		hunnor.vm.network "forwarded_port", guest: 8983, host: 8983
		hunnor.vm.provider "virtualbox" do |vb|
			vb.memory = 2048
			vb.name = "HunNor"
		end
		hunnor.vm.provision "ansible" do |ansible|
			ansible.playbook = "ansible/playbook.yml"
		end
	end

	config.vm.define "rancher", autostart: false do |rancher|
		rancher.vm.box = "box-cutter/ubuntu1604"
		rancher.vm.hostname = "rancher"
		rancher.vm.network "public_network", :mac => "0800275E876B"
		rancher.vm.provider "virtualbox" do |vb|
			vb.cpus = 2
			vb.memory = 8192
			vb.name = "Rancher"
		end
		rancher.vm.provision "ansible" do |ansible|
			ansible.playbook = "ansible/playbook.yml"
		end
	end

end
