- apt:
    name: python3-docker
    state: present
  become: yes

- docker_container:
    image: rancher/rancher:stable
    name: rancher
    restart_policy: unless-stopped
    published_ports:
      - 80:80
      - 443:443
  become: yes
