- lineinfile:
    dest: "/etc/default/hunnor-solr.in.sh"
    state: present
    line:  SOLR_OPTS="$SOLR_OPTS -Dsolr.allow.unsafe.resourceloading=true"
  sudo: yes

- lineinfile:
    dest: "/etc/default/hunnor-solr.in.sh"
    state: present
    line:  SOLR_OPTS="$SOLR_OPTS -Dlucene.match.version={{solr.version}}"
  sudo: yes

- lineinfile:
    dest: "/etc/default/hunnor-solr.in.sh"
    state: present
    line:  SOLR_HOME={{hunnor.apps.dir}}/solr-cores
  sudo: yes

- git:
    dest: "{{hunnor.apps.dir}}/solr-cores"
    repo: https://github.com/hunnor-dict/solr-cores.git
  become: yes
  become_user: "{{hunnor.user.name}}"

- file:
    group: "{{hunnor.user.group}}"
    owner: "{{hunnor.user.name}}"
    path: "{{hunnor.apps.dir}}/repo/dump"
    state: directory
  sudo: yes

- get_url:
    dest: /tmp/HunNor-XML-HN.xml.gz
    url: https://dl.dropboxusercontent.com/s/5o4n99n7xvmcu7h/HunNor-XML-HN.xml.gz?dl=0
  sudo: yes

- command: creates=/tmp/HunNor-XML-HN.xml gunzip -k /tmp/HunNor-XML-HN.xml.gz
  sudo: yes

- command: creates="{{hunnor.apps.dir}}/repo/dump/HunNor-XML-HN.xml" cp /tmp/HunNor-XML-HN.xml {{hunnor.apps.dir}}/repo/dump/HunNor-XML-HN.xml
  sudo: yes

- file:
    group: "{{hunnor.user.group}}"
    owner: "{{hunnor.user.name}}"
    path: "{{hunnor.apps.dir}}/repo/dump/HunNor-XML-HN.xml"
  sudo: yes

- get_url:
    dest: /tmp/HunNor-XML-NH.xml.gz
    url: https://dl.dropboxusercontent.com/s/915ltjp7eh26aag/HunNor-XML-NH.xml.gz?dl=0
  sudo: yes

- command: creates=/tmp/HunNor-XML-NH.xml gunzip -k /tmp/HunNor-XML-NH.xml.gz
  sudo: yes

- command: creates="{{hunnor.apps.dir}}/repo/dump/HunNor-XML-NH.xml" cp /tmp/HunNor-XML-NH.xml {{hunnor.apps.dir}}/repo/dump/HunNor-XML-NH.xml
  sudo: yes

- file:
    group: "{{hunnor.user.group}}"
    owner: "{{hunnor.user.name}}"
    path: "{{hunnor.apps.dir}}/repo/dump/HunNor-XML-NH.xml"
  sudo: yes

- lineinfile:
    dest: "/etc/default/hunnor-solr.in.sh"
    state: present
    line:  SOLR_OPTS="$SOLR_OPTS -Dhunnor.dump.dir={{hunnor.apps.dir}}/repo/dump"
  sudo: yes

- lineinfile:
    dest: "/etc/default/hunnor-solr.in.sh"
    state: present
    line:  SOLR_OPTS="$SOLR_OPTS -Dhunnor.dump.file.hu=HunNor-XML-HN.xml"
  sudo: yes

- lineinfile:
    dest: "/etc/default/hunnor-solr.in.sh"
    state: present
    line:  SOLR_OPTS="$SOLR_OPTS -Dhunnor.dump.file.nb=HunNor-XML-HN.xml"
  sudo: yes

- file:
    group: "{{hunnor.user.group}}"
    owner: "{{hunnor.user.name}}"
    path: "/var/opt/solr/data"
    state: directory
  sudo: yes
