version: '2.1'

services:

  solr-cores:
    image: hunnordict/solr-cores
    volumes:
      - ${HUNNOR_XML_DUMP_DIR:-/tmp}:/opt/hunnor-dict/repo/dump
    ports:
      - "${HUNNOR_SOLR_PORT:-8983}:8983"

  web-spring:
    image: hunnordict/web-spring
    depends_on:
      - solr-cores
    links:
      - solr-cores:solr
    ports:
      - "${HUNNOR_WEB_PORT:-8080}:8080"
    command: --net.hunnor.dict.search.solr.url=http://solr:8983/solr
