- user:
    name: "{{solr.user.name}}"
    password: "{{solr.user.password}}"
  sudo: yes

- get_url:
    dest: /tmp/solr-{{solr.version}}.tgz
    url: http://apache.uib.no/lucene/solr/{{solr.version}}/solr-{{solr.version}}.tgz
  sudo: yes

- file:
    group: "{{solr.user.group}}"
    owner: "{{solr.user.name}}"
    path: "{{solr.dir}}"
    state: directory
  sudo: yes

- unarchive:
    copy: no
    creates: "{{solr.dir}}/solr-{{solr.version}}"
    dest: "{{solr.dir}}"
    src: /tmp/solr-{{solr.version}}.tgz
  sudo: yes

- file:
    group: "{{solr.user.group}}"
    owner: "{{solr.user.name}}"
    path: "{{solr.dir}}/solr-{{solr.version}}"
    recurse: yes
  sudo: yes

- command: creates="/etc/init.d/{{solr.name}}" cp {{solr.dir}}/solr-{{solr.version}}/bin/init.d/solr /etc/init.d/{{solr.name}}
  sudo: yes

- replace:
    dest: "/etc/init.d/{{solr.name}}"
    regexp: SOLR_INSTALL_DIR="/opt/solr"
    replace: SOLR_INSTALL_DIR="{{solr.dir}}/solr-{{solr.version}}"
  sudo: yes

- replace:
    dest: "/etc/init.d/{{solr.name}}"
    regexp: SOLR_ENV="/etc/default/solr.in.sh"
    replace: SOLR_ENV="/etc/default/{{solr.name}}.in.sh"
  sudo: yes

- replace:
    dest: "/etc/init.d/{{solr.name}}"
    regexp: RUNAS="solr"
    replace: RUNAS="{{solr.user.name}}"
  sudo: yes

- command: creates="/etc/default/{{solr.name}}.in.sh" cp {{solr.dir}}/solr-{{solr.version}}/bin/solr.in.sh /etc/default/{{solr.name}}.in.sh
  sudo: yes
