ALTER TABLE BOYING_GRUPPER ADD CONSTRAINT PRIMARY KEY (BOY_GRUPPE);
SHOW WARNINGS;

ALTER TABLE BOYING ADD CONSTRAINT PRIMARY KEY (BOY_NUMMER, BOY_GRUPPE);
SHOW WARNINGS;
ALTER TABLE BOYING ADD CONSTRAINT FK_BOYING_BOYING_GRUPPER FOREIGN KEY (BOY_GRUPPE) REFERENCES BOYING_GRUPPER (BOY_GRUPPE);
SHOW WARNINGS;

ALTER TABLE PARADIGME ADD CONSTRAINT PRIMARY KEY (PARADIGME_ID);
SHOW WARNINGS;
ALTER TABLE PARADIGME ADD CONSTRAINT FK_PARADIGME_BOY_GRUPPE FOREIGN KEY (BOY_GRUPPE) REFERENCES BOYING_GRUPPER (BOY_GRUPPE);
SHOW WARNINGS;

ALTER TABLE PARADIGME_BOYING ADD CONSTRAINT PRIMARY KEY (PARADIGME_ID, BOY_NUMMER, BOY_GRUPPE);
SHOW WARNINGS;
ALTER TABLE PARADIGME_BOYING ADD CONSTRAINT FK_PARADIGME_BOYING_PARADIGME FOREIGN KEY (PARADIGME_ID) REFERENCES PARADIGME (PARADIGME_ID);
SHOW WARNINGS;
ALTER TABLE PARADIGME_BOYING ADD CONSTRAINT FK_PARADIGME_BOYING_BOYING FOREIGN KEY (BOY_NUMMER, BOY_GRUPPE) REFERENCES BOYING (BOY_NUMMER, BOY_GRUPPE);
SHOW WARNINGS;

ALTER TABLE LEMMA ADD CONSTRAINT PRIMARY KEY (LEMMA_ID);
SHOW WARNINGS;

ALTER TABLE LEMMA_PARADIGME ADD CONSTRAINT PRIMARY KEY (LEMMA_ID, PARADIGME_ID);
SHOW WARNINGS;
    DELETE FROM LEMMA_PARADIGME WHERE LEMMA_ID = 159286; -- PATCH
ALTER TABLE LEMMA_PARADIGME ADD CONSTRAINT FK_LEMMA_PARADIGME_LEMMA FOREIGN KEY (LEMMA_ID) REFERENCES LEMMA (LEMMA_ID);
SHOW WARNINGS;
ALTER TABLE LEMMA_PARADIGME ADD CONSTRAINT FK_LEMMA_PARADIGME_PARADIGME FOREIGN KEY (PARADIGME_ID) REFERENCES PARADIGME (PARADIGME_ID);
SHOW WARNINGS;

ALTER TABLE FULLFORMSLISTE ADD CONSTRAINT PRIMARY KEY (LEMMA_ID, OPPSLAG, TAG, PARADIGME_ID, BOY_NUMMER);
SHOW WARNINGS;
    DELETE FROM FULLFORMSLISTE WHERE LEMMA_ID NOT IN (SELECT LEMMA_ID FROM LEMMA); -- PATCH
ALTER TABLE FULLFORMSLISTE ADD CONSTRAINT FK_FULLFORMSLISTE_LEMMA FOREIGN KEY (LEMMA_ID) REFERENCES LEMMA (LEMMA_ID);
SHOW WARNINGS;

ALTER TABLE LEDDANALYSE ADD CONSTRAINT PRIMARY KEY (LEDDANALYSE_ID);
SHOW WARNINGS;
ALTER TABLE LEDDANALYSE ADD CONSTRAINT FK_LEDDANALYSE_LEMMA FOREIGN KEY (LEMMA_ID) REFERENCES LEMMA (LEMMA_ID);
SHOW WARNINGS;
