SELECT LEMMA_ID, OPPSLAG, PARADIGME_ID, BOY_NUMMER FROM FULLFORMSLISTE
WHERE PARADIGME_ID <> '000'
ORDER BY LEMMA_ID, PARADIGME_ID, BOY_NUMMER
INTO OUTFILE '/data/forms-full.csv'
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

SELECT LEMMA.LEMMA_ID, LEMMA.GRUNNFORM, PARADIGME_BOYING.BOY_UTTRYKK, PARADIGME.PARADIGME_ID, PARADIGME_BOYING.BOY_NUMMER
FROM LEMMA
  INNER JOIN LEMMA_PARADIGME ON LEMMA.LEMMA_ID = LEMMA_PARADIGME.LEMMA_ID
  INNER JOIN PARADIGME ON LEMMA_PARADIGME.PARADIGME_ID = PARADIGME.PARADIGME_ID
  INNER JOIN BOYING ON PARADIGME.BOY_GRUPPE = BOYING.BOY_GRUPPE
  LEFT JOIN PARADIGME_BOYING ON PARADIGME.PARADIGME_ID = PARADIGME_BOYING.PARADIGME_ID AND BOYING.BOY_NUMMER = PARADIGME_BOYING.BOY_NUMMER
ORDER BY LEMMA.LEMMA_ID, PARADIGME.PARADIGME_ID, BOYING.BOY_NUMMER
INTO OUTFILE '/data/forms-join.csv'
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';
