- command: timedatectl set-timezone Europe/Oslo
  become: yes

- apt:
    update_cache: yes
  become: yes

- apt:
    name: mc
    state: present
  become: yes

- apt:
    name: cron-apt
    state: present
  become: yes

- lineinfile:
    dest: /etc/cron-apt/config
    line: MAILON=upgrade
    state: present
  become: yes

- lineinfile:
    dest: /etc/cron-apt/config
    line: MAILTO={{hunnor_sysadmin_email}}
    state: present
  become: yes

- lineinfile:
    dest: /etc/cron-apt/action.d/3-download
    line: dist-upgrade -d -y -o APT::Get::Show-Upgraded=true
    state: absent
  become: yes

- lineinfile:
    dest: /etc/cron-apt/action.d/3-download
    line: upgrade -d -y -o APT::Get::Show-Upgraded=true
    state: present
  become: yes

- debconf:
    name: nagios3-cgi
    question: nagios3/adminpassword
    value: "{{hunnor_nagios_user_password}}"
    vtype: password
  become: yes

- debconf:
    name: nagios3-cgi
    question: nagios3/adminpassword-repeat
    value: "{{hunnor_nagios_user_password}}"
    vtype: password
  become: yes

- apt:
    name: nagios3
    state: present
  become: yes

- file:
    path: /etc/nagios3/conf.d
    state: absent
  become: yes

- file:
    path: /etc/nagios3/conf.d
    state: directory
  become: yes

- copy:
    src: nagios/
    dest: /etc/nagios3/conf.d
  become: yes

- template:
    dest: /etc/nagios3/conf.d/contacts.cfg
    src: contacts.cfg.j2
  become: yes

- template:
    dest: /etc/nagios3/conf.d/localhost.cfg
    src: localhost.cfg.j2
  become: yes

- command: "htpasswd -b -c /etc/nagios3/htpasswd.users {{hunnor_nagios_user_name}} {{hunnor_nagios_user_password}}" 
  become: yes

- apt:
    name: php-fpm
    state: present
  become: yes

- command: "a2dismod php7.2"
  become: yes

- command: "a2enmod proxy_fcgi setenvif"
  become: yes

- command: "a2enconf php7.2-fpm"
  become: yes

- command: "a2dismod mpm_prefork"
  become: yes

- command: "a2enmod mpm_event"
  become: yes

- service:
    name: nagios3
    state: restarted
  become: yes

- debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: Internet Site
    vtype: select
  become: yes

- debconf:
    name: postfix
    question: postfix/mailname
    value: hunnor
    vtype: string
  become: yes

- apt:
    name: postfix
    state: present
  become: yes

- apt_repository:
    repo: ppa:certbot/certbot
  become: yes

- apt:
    name: python-certbot-apache
    state: present
  become: yes

- template:
    dest: /home/{{hunnor_user_name}}/crontab
    src: crontab.j2
  become: yes
  become_user: "{{hunnor_user_name}}"

- command: crontab /home/{{hunnor_user_name}}/crontab
  become: yes
  become_user: "{{hunnor_user_name}}"

- file:
    path: /home/{{hunnor_user_name}}/crontab
    state: absent
  become: yes
  become_user: "{{hunnor_user_name}}"

- copy:
    dest: /home/{{hunnor_user_name}}/
    group: "{{hunnor_user_name}}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{hunnor_user_name}}"
    src: start-dropbox.sh
  become: yes
