- get_url:
    dest: /tmp/HunNor-MySQL.sql.gz
    url: https://dl.dropboxusercontent.com/s/fpcjv7jfktkkflt/HunNor-MySQL.sql.gz?dl=0
  sudo: yes

- command: creates=/tmp/HunNor-MySQL.sql gunzip -k /tmp/HunNor-MySQL.sql.gz
  sudo: yes

- command: mysql -u root -p{{mysql.root.password}} -e "CREATE DATABASE IF NOT EXISTS {{hunnor.db.name}};"
  sudo: yes

- command: mysql -u root -p{{mysql.root.password}} -e "CREATE USER IF NOT EXISTS '{{hunnor.db.user.name}}'@'localhost' IDENTIFIED BY '{{hunnor.db.user.password}}';"
  sudo: yes

- command: mysql -u root -p{{mysql.root.password}} -e "GRANT SELECT, UPDATE, INSERT, DELETE ON {{hunnor.db.name}}.* TO '{{hunnor.db.user.name}}'@'localhost' IDENTIFIED BY '{{hunnor.db.user.password}}';"
  sudo: yes

- command: mysql -u root -p{{mysql.root.password}} -D {{hunnor.db.name}} -e "source /tmp/HunNor-MySQL.sql;"
  sudo: yes

- command: mysql -u root -p{{mysql.root.password}} -D {{hunnor.db.name}} -e "CREATE TABLE IF NOT EXISTS hn_log_edit (editor_id varchar(16) NOT NULL, lang varchar(4) NOT NULL, entry_id int(11) NOT NULL, action varchar(8) NOT NULL, timestamp bigint(11) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;"
  sudo: yes

- command: mysql -u root -p{{mysql.root.password}} -D {{hunnor.db.name}} -e "CREATE TABLE IF NOT EXISTS hn_adm_editors (id varchar(16) NOT NULL, provider varchar(16) NOT NULL, uid varchar(64) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;"
  sudo: yes

- git:
    dest: "{{hunnor.apps.dir}}/admin-rails"
    repo: https://github.com/hunnor-dict/admin-rails.git
  become: yes
  become_user: "{{hunnor.user.name}}"

- apt:
    name: nodejs
    state: present
  sudo: yes

- command: gem install bundler
  sudo: yes

- command: chdir="{{hunnor.apps.dir}}/admin-rails" bundle install
  sudo: yes

- lineinfile:
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    state: present
    line:  sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
  sudo: yes

- service:
    name: mysql
    state: restarted
  sudo: yes
