- template:
    dest: /etc/apache2/sites-available/001-hunnor-dict.conf
    src: hunnor-dict.conf.j2
  sudo: yes

- file:
    dest: /etc/apache2/sites-enabled/001-hunnor-dict.conf
    src: /etc/apache2/sites-available/001-hunnor-dict.conf
    state: link
  sudo: yes

- template:
    dest: /etc/apache2/sites-available/002-hunnor-dict-admin.conf
    src: hunnor-dict-admin.conf.j2
  sudo: yes

- file:
    dest: /etc/apache2/sites-enabled/002-hunnor-dict-admin.conf
    src: /etc/apache2/sites-available/002-hunnor-dict-admin.conf
    state: link
  sudo: yes
