CREATE TABLE IF NOT EXISTS BOYING (
  BOY_NUMMER int(2) NOT NULL,
  BOY_GRUPPE varchar(20) NOT NULL,
  BOY_TEKST varchar(100) NOT NULL,
  ORDBOK_TEKST varchar(200)
);

CREATE TABLE IF NOT EXISTS BOYING_GRUPPER (
  BOY_GRUPPE varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS FULLFORMSLISTE (
  LEMMA_ID int(8) NOT NULL,
  OPPSLAG varchar(100) NOT NULL,
  TAG varchar(750) NOT NULL,
  PARADIGME_ID varchar(5) NOT NULL,
  BOY_NUMMER int(2) NOT NULL,
  FRADATO varchar(10) NOT NULL,
  TILDATO varchar(10) NOT NULL,
  NORMERING varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEMMA (
  LEMMA_ID int(8) NOT NULL,
  GRUNNFORM varchar(100) NOT NULL
);

CREATE INDEX LEMMA_LEMMA_ID ON LEMMA(LEMMA_ID);
CREATE INDEX LEMMA_GRUNNFORM ON LEMMA(GRUNNFORM);

CREATE TABLE IF NOT EXISTS LEMMA_PARADIGME (
  LEMMA_ID int(8) NOT NULL,
  PARADIGME_ID varchar(5) NOT NULL,
  NORMERING varchar(20) DEFAULT 'normert' NOT NULL,
  FRADATO varchar(10) DEFAULT '1900' NOT NULL,
  TILDATO varchar(10) DEFAULT '4000' NOT NULL,
  KOMMENTAR varchar(1000)
);

CREATE INDEX LEMMA_PARADIGME_LEMMA_ID ON LEMMA_PARADIGME(LEMMA_ID);
CREATE INDEX LEMMA_PARADIGME_PARADIGME_ID ON LEMMA_PARADIGME(PARADIGME_ID);

CREATE TABLE IF NOT EXISTS PARADIGME (
  PARADIGME_ID varchar(5) NOT NULL,
  BOY_GRUPPE varchar(20) NOT NULL,
  ORDKLASSE varchar(50) NOT NULL,
  ORDKLASSE_UTDYPING varchar(100) DEFAULT NULL,
  FORKLARING varchar(100) DEFAULT NULL,
  DOEME varchar(100) DEFAULT NULL,
  ID int(5) NOT NULL
);

CREATE INDEX PARADIGME_PARADIGME_ID ON PARADIGME(PARADIGME_ID);

CREATE TABLE IF NOT EXISTS PARADIGME_BOYING (
  PARADIGME_ID varchar(5) NOT NULL,
  BOY_NUMMER int(2) NOT NULL,
  BOY_GRUPPE varchar(20) NOT NULL,
  BOY_UTTRYKK varchar(50) DEFAULT NULL
);

CREATE INDEX PARADIGME_BOYING_PARADIGME_ID ON PARADIGME_BOYING(PARADIGME_ID);
