- apt:
    name: python3-docker
    state: present
  become: yes

- user:
    append: yes
    groups: docker
    name: "{{hunnor_user_name}}"
  become: yes

- docker_container:
    env:
      TZ: Europe/Oslo
    image: hunnordict/word-trainer
    name: word-trainer
    published_ports:
      - 127.0.0.1:8081:80
    restart_policy: always
  become: yes
  become_user: "{{hunnor_user_name}}"

- copy:
    dest: /home/{{hunnor_user_name}}/
    group: "{{hunnor_user_group}}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{hunnor_user_name}}"
    src: docker-update-word-trainer.sh
  become: yes
